### ISSUE TITLE
Has anyone got this running in a web api project?

### ISSUE THREAD

**Issue by murrayLuke** [codekoenig/AspNetCore.Identity.DocumentDb#10]
WebApi has no configure services method so I'm struggling to get this to run in a webapi 2 project on aspnet

**Comment by codekoenig** [comment]
Sorry I somehow overlooked your question. I'm sure you figured this out by now, but just for reference: this is a DocumentDb storage provider for ASP.NET _Core_, so it won't work with the "classic" WebAPI from the full .NET Framework.

You should look into projects like https://github.com/tracker086/DocumentDB.AspNet.Identity that support the classic WebAPI/Identity frameworks.
