### ISSUE TITLE
Not able to compile samples in Visual Studio for Mac

### ISSUE THREAD

**Issue by daspuru** [codekoenig/AspNetCore.Identity.DocumentDb#11]
Hello,

I can not get the project to run, as the project reference in IdentitySample.Mvc to AspNetCore.Identity.DocumentDb states: "Incompatible target framework 4.6.1".

And the other problem is that the packages are unable to be restored, at the end of the Package Console output this is the message:

`Errors in /Users/daniel/Documents/Xamarin/AspNetCore.Identity.DocumentDb/src/AspNetCore.Identity.DocumentDb/AspNetCore.Identity.DocumentDb.csproj
    Package Microsoft.Azure.DocumentDB.Core 1.1.2 is not compatible with net46 (.NETFramework,Version=v4.6). Package Microsoft.Azure.DocumentDB.Core 1.1.2 supports: netstandard1.6 (.NETStandard,Version=v1.6)
    One or more packages are incompatible with .NETFramework,Version=v4.6.`

**Comment by codekoenig** [comment]
I don't have any experience with VS for Mac, but as the full .NET Framework is not available on this platform, I suppose you could easily fix this by removing .NET Framework 4.6 as a build target and only build against .NET Core. 

Remove this part in .csproj and see how it goes:

```
<ItemGroup Condition=" '$(TargetFramework)' == 'net46' ">
    <PackageReference Include="Microsoft.Azure.DocumentDB" Version="1.12.0" />
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
</ItemGroup>
```
