### ISSUE TITLE
AspNetCore 2.0

### ISSUE THREAD

**Issue by jesusmtq** [codekoenig/AspNetCore.Identity.DocumentDb#13]
Hello,

Will this package be updated to support latest ASP.NET Core 2.0 ?

https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x

Best regards

**Comment by codekoenig** [comment]
Definitely, but work has not started yet. I will look into this in the next couple of weeks.

**Comment by louislewis2** [comment]
Please see https://github.com/codekoenig/AspNetCore.Identity.DocumentDb/pull/14

**Comment by jesusmtq** [comment]
@louislewis2 Thanks for that! And for keeping backwards compability, very nice :)

**Comment by louislewis2** [comment]
@jesusmtq Thanks for the shout out. I'm happy it was able to help you.

**Comment by projecteon** [comment]
When can we expect a nuget release of this?

**Comment by codekoenig** [comment]
@projecteon Couple of days ... cautiously I'd say maybe tomorrow, but if not I should find the time on the weekend.

**Comment by codekoenig** [comment]
Fixed in #14

**Comment by codekoenig** [comment]
Fixed in #14

**Comment by codekoenig** [comment]
@projecteon Version 2.0 of the package with .NET Core 2.0 support is now published and should appear on NuGet soon.
