### ISSUE TITLE
Use type FullName for querying documents

### ISSUE THREAD

**Issue by rbickel** [codekoenig/AspNetCore.Identity.DocumentDb#4]
To be able to store multiple app in the same collection, using Fullname for DocumentType instead of Name would bring this benefit I guess.

**Comment by codekoenig** [comment]
Good suggestion, I'll look into this.

**Comment by codekoenig** [comment]
@nemesis1203 I thought about this and came to the conclusion that I don't want to have the FullName as a default. It has to be an indexed field and thus can cause a lot of storage overhead if you don't need the FullName, which will be the case in most scenarios I assume. Also I would break current implementations, which would be OK considering the Beta status of the NuGet package, but still, if you can avoid this ...

The other possibility was to make it configurable, but that would be hard and intransparent/hacky the way it could be done (considering creating the User and Role instances is not in the control of the persistence provider).

So what I actually would suggest if you need this is to simply create your own User and Role classes and inherit from `DocumentDbIdentityUser` and `DocumentDbIdentityRole` and overwrite the `DocumentType` property:

```csharp
public class MyCustomUser : DocumentDbIdentityUser<DocumentDbIdentityRole>
{
    public override string DocumentType
    {
        get
        {
            return this.GetType().FullName;
        }
    }
}
```

I think that would be the cleanest way to solve your requirement. Do you agree?
