### ISSUE TITLE
UserStore incorrectly expect roleName instead of normalizedRoleName

### ISSUE THREAD

**Issue by phongphan** [codekoenig/AspNetCore.Identity.DocumentDb#5]
The AspNetCore.Identity seems to expected [`NormalizedRoleName`](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/UserStore.cs#L663).

And it would break if RoleName is difference from NormalizedRoleName. Eg. "ADMIN" vs "admin".

It could be reproduce by changing the `ShouldAddUserToRole` test case:
from
`DocumentDbIdentityRoleBuilder.Create()`
to
`DocumentDbIdentityRoleBuilder.Create("ANonNormalizedString")`

**Comment by codekoenig** [comment]
Thanks. `Microsoft.AspNetCore.Identity.IUserRoleStore<TUser>` defines the param name as `roleName` only, but as ASP.NET Core Identity will always provide the normalized role name here, we should go with `normalizedRoleName` in the implementation of the interface.

**Comment by phongphan** [comment]
Not just that.

The problems still there if `Name != NormalizedName`. Which will arise when using it from UserManager and RoleManager.
For example: https://github.com/codekoenig/AspNetCore.Identity.DocumentDb/blob/be3bb3213ab9dd389f0f254cd867cb734e9263a0/src/AspNetCore.Identity.DocumentDb/Stores/DocumentDbUserStore.cs#L505

Both of them (user and role manager) are implicitly convert Name to NormalizedName before interacting with the store (the user need to ensure that all of them must be using the same Normalizer, which is tedious but not our problem here.)

I'll try to create the test cases if I have the free time

**Comment by codekoenig** [comment]
Ah yea, right, I missed that I compare it to the wrong field. I will work on it later today.

**Comment by codekoenig** [comment]
Thanks @phongphan that was a pretty nasty bug. I checked in the changes and I added some tests and adapted the test data helpers to always generate non-normalized ids and names. I'll do another code review but hope I found all occasions now.

**Comment by phongphan** [comment]
That's great!

It's very strange design from their side though

**Comment by codekoenig** [comment]
Yea, but I think it makes sense that they see the normalizing in the domain of ASP.NET Identity and not of the storage provider. But sometimes the theoretically right solution is not always the most practicable.

For me, it would have helped if they at least named the `roleName` parameters in `IUserRoleStore` as `normalizedRoleName`, like they did in every other interface when a normalized name is expected. I think that's what lead me to think in the wrong way. But no excuses, no later than when I typed a comparison between roleName and normalizedRoleName the alarm bells should have ringed :)
